### ISSUE TITLE
Is checking that directory exists required?

### ISSUE THREAD

**Issue by rutsky** [gemini-project/ansible-role-ansible-controller#3]
For example [here](https://github.com/gemini-project/ansible-role-ansible-controller/blob/bde2479f4b3abef3797c129d1e2b0c5bf51f40ca/tasks/kube_download.yml#L2):

```
- name: Determine if Kubernetes download directory exists
  stat: path={{ kube_download_dir }}
  register: kdd
  changed_when: false
  always_run: yes

- name: Create Kubernetes download directory
  file:
    path: "{{ kube_download_dir }}"
    state: directory
    owner: apache
    group: apache
    mode: '0701'
  when: not kdd.stat.exists
```

I would do just:

```
- name: Create Kubernetes download directory
  file:
    path: "{{ kube_download_dir }}"
    state: directory
    owner: apache
    group: apache
    mode: '0701'
```

I believe Ansible is smart enough to not to touch directory is it already exists (and have specified parameters: owner, group, mode).
